import { Hero } from "./hero"

export const HERO: Hero[] = [
  {id: 1, img: '/assets/img/1.jpg', title: 'Wolverine', description: 'The first Wolverine was a four issue limited series written by Chris Claremont with pencils by Frank Miller, inks by Joe Rubinstein, letters by Tom Orzechowski, and colors by Glynis Wein. Marvel Comics published the series from September to December of 1982. This story arc covers the events leading up to Wolverine\'s engagement to Mariko Yashida.'},
  {id: 2, img: '/assets/img/2.jpg', title: 'Iron-man', description: 'The first Wolverine was a four issue limited series written by Chris Claremont with pencils by Frank Miller, inks by Joe Rubinstein, letters by Tom Orzechowski, and colors by Glynis Wein. Marvel Comics published the series from September to December of 1982. This story arc covers the events leading up to Wolverine\'s engagement to Mariko Yashida.'},
  {id: 3, img: '/assets/img/3.jpg', title: 'Captain America', description: 'The first Wolverine was a four issue limited series written by Chris Claremont with pencils by Frank Miller, inks by Joe Rubinstein, letters by Tom Orzechowski, and colors by Glynis Wein. Marvel Comics published the series from September to December of 1982. This story arc covers the events leading up to Wolverine\'s engagement to Mariko Yashida.'},
  {id: 4, img: '/assets/img/4.jpg', title: 'Green Lantern', description: 'The first Wolverine was a four issue limited series written by Chris Claremont with pencils by Frank Miller, inks by Joe Rubinstein, letters by Tom Orzechowski, and colors by Glynis Wein. Marvel Comics published the series from September to December of 1982. This story arc covers the events leading up to Wolverine\'s engagement to Mariko Yashida.'},
  {id: 5, img: '/assets/img/5.jpg', title: 'Batman', description: 'The first Wolverine was a four issue limited series written by Chris Claremont with pencils by Frank Miller, inks by Joe Rubinstein, letters by Tom Orzechowski, and colors by Glynis Wein. Marvel Comics published the series from September to December of 1982. This story arc covers the events leading up to Wolverine\'s engagement to Mariko Yashida.'},
  {id: 6, img: '/assets/img/6.jpg', title: 'Spider-man', description: 'The first Wolverine was a four issue limited series written by Chris Claremont with pencils by Frank Miller, inks by Joe Rubinstein, letters by Tom Orzechowski, and colors by Glynis Wein. Marvel Comics published the series from September to December of 1982. This story arc covers the events leading up to Wolverine\'s engagement to Mariko Yashida.'},
]
